### ISSUE TITLE
ほしい機能

### ISSUE THREAD

**Issue by grazios** [use-joho/2017_freshmansystem#1]
ほしい機能をひたすら書く

**Comment by grazios** [comment]
- [ ] ログイン

**Comment by grazios** [comment]
ステージ情報追加

**Comment by grazios** [comment]
ランキング

**Comment by grazios** [comment]
武器別勝率

**Comment by grazios** [comment]
ピボットテーブル
武器とステージとルールと時間？

**Comment by shunkoyama** [comment]
○武器毎、ステージ&ルール毎の勝率を表示する機能（武器は勝率、使用率でソート可能）

○直近10戦の勝率上位3つのステージ&ルールを表示（まだ行ったことがないものは非表示）

○合計勝率の他に直近××戦の勝率を表示する機能

○ランダムにステージルール、武器（各プレイヤー毎、武器ジャンルで選択したものは候補から外せる）を指定する機能

○試合結果を記入、送信すると自画面に遷移。記入したステージ、武器、勝敗数とキルレを表示する機能

**Comment by grazios** [comment]
ギアのセット

でもギアは結構コロコロ変えたり武器に合わせて統一していたりするので正直入力が面倒くさいかもしれない。

**Comment by shunkoyama** [comment]
フレンド機能。フレンド内でのランキングや、フレンドの詳細情報表示

**Comment by WataruKadomatsu** [comment]
各ブキ事(もしくは種類事)の性能
射程や威力などを5段階で評価する

**Comment by grazios** [comment]
一旦締め切り
